#!/bin/bash
# Usage: copy this file to the instance and run it once, e.g. /bin/bash alt_deploy

PROJECT_DIR=/home/ec2-user/fsdf-elvis
APACHE_CONFIG_DIR=/home/ec2-user/apache-configuration
HTTP_CONFIG_DIR=/etc/httpd/conf.d

PROXY_FILE_NAME=proxies.conf
PROXY_SOURCE=$APACHE_CONFIG_DIR/config/$PROXY_FILE_NAME

FSDF_SERVICE_NAME=fsdf
FSDF_SERVICE_SOURCE=$PROJECT_DIR/code-deploy/fsdf
FSDF_SERVICE_TARGET=/etc/init.d/fsdf

ELEVATION_CONFIG_FILE_NAME=elevation.conf
ELEVATION_CONFIG_SOURCE=$APACHE_CONFIG_DIR/config/$ELEVATION_CONFIG_FILE_NAME

LOGROTATE_SOURCE_DIR=/home/ec2-user/apache-configuration/config/logrotate
LOGROTATE_TARGET_DIR=/etc/logrotate.d

cd /home/ec2-user
sudo yum update -y
sudo curl --silent --location https://rpm.nodesource.com/setup_12.x | sudo bash -

sudo yum -y install nodejs

sudo yum install -y gcc-c++ make
sudo yum install -y httpd
sudo yum install -y git
sudo npm install -g forever
sudo npm install -g bower

git clone https://github.com/GeoscienceAustralia/fsdf-elvis.git
git clone https://github.com/GeoscienceAustralia/apache-configuration.git

cd fsdf-elvis
npm install
bower install

# Sets up Apache HTTP service
sudo cp "$PROXY_SOURCE" "$HTTP_CONFIG_DIR"
sudo cp "$ELEVATION_CONFIG_SOURCE" "$HTTP_CONFIG_DIR"

# Sets up logging
sudo cp -f "$LOGROTATE_SOURCE_DIR"/* "$LOGROTATE_TARGET_DIR"

# Creates a SYSV service and autostarts it
sudo cp "$FSDF_SERVICE_SOURCE" /etc/init.d
sudo chmod +x $FSDF_SERVICE_TARGET
sudo service $FSDF_SERVICE_NAME start
sudo chkconfig $FSDF_SERVICE_NAME on

# To make sure in the right directory
cd $PROJECT_DIR
bower update

# Copy static content to Apache
sudo cp -rf dist/* /var/www/html

sudo systemctl start httpd
sudo systemctl enable httpd
